// FAKE DATA
export const books = [
  {
    id: 1,
          title: "Tokyo Mew Mew",
          url: "https://ia902703.us.archive.org/view_archive.php?archive=/21/items/olcovers199/olcovers199-L.zip&file=1992653-L.jpg",
          originalPrice: 15.95,
          salePrice: 14.95,
          rating: 4.5,
          summary: "In Tokyo, Japan, a young girl named Ichigo Momomiya attends an endangered species exhibit with her crush Masaya Aoyama. After an earthquake, Ichigo and four other girls are bathed in a strange light. A cat appears before Ichigo, then merges with her.",
        },
        {
          id: 2,
          title: "Ouran High School Host Club",
          url: "https://covers.openlibrary.org/b/id/8972961-L.jpg",
          originalPrice: 18.95,
          salePrice: 14.95,
          rating: 5,
          summary: "Haruhi Fujioka stumbles onto the Ouran Host Club and breaks a priceless vase. Now she has to work as a Host (disguised as a boy) to pay off her debt to the club.",
        },
        {
          id: 3,
          title: "Inuyasha",
          url: "https://covers.openlibrary.org/b/id/7802605-L.jpg",
          originalPrice: 13.95,
          salePrice: 10.95,
          rating: 4,
          summary: "Kagome Higurashi, a 15-year-old junior high school student, is dragged into the Bone Eater's Well by Mistress Centipede, an insect-demon. She escapes and emerges in the past. Kagome turns out to be the reincarnation from the deceased maiden Kikyo, with the sacred Shikon Jewel also reborn inside her body.",
        },
        {
          id: 4,
          title: "Fruits Basket",
          url: "https://ia800602.us.archive.org/view_archive.php?archive=/12/items/olcovers693/olcovers693-L.zip&file=6932408-L.jpg",
          originalPrice: 15.95,
          salePrice: 14.95,
          rating: 5,
          summary: "After a family tragedy turns her life upside down, plucky high schooler Tohru Honda takes matters into her own hands and moves out...into a tent! Unfortunately for her, she pitches her new home on private land belonging to the mysterious Sohma clan, and it isn't long before the owners discover her secret.",
        },
        {
          id: 5,
          title: "Toilet-Bound Hanako-Kun",
          url: "https://covers.openlibrary.org/b/id/9352506-L.jpg",
          originalPrice: 15.95,
          salePrice: null,
          rating: 5,
          summary: "The story follows Nene Yashiro, a fan of the occult who dreams of having a perfect romance. One of the seven mysteries of the Kamome Academy she attends says that a girl called Hanako-san haunts the third-floor girls' bathroom in the old school building.",
        },
        {
          id: 6,
          title: "Gakuen Alice",
          url: "https://covers.openlibrary.org/b/id/10673907-L.jpg",
          originalPrice: 13.95,
          salePrice: null,
          rating: 4,
          summary: "Young Mikun Sakura is amazed about her best friend Hotaru being enrolled at a Geniuses only school as all around the area where she lives people are going crazy about the news. Although she is not any form of genius, she is an Alice, or special kind of person, but when Hotaru leaves for the school that same day she got the invitation, her friend is angry at them for separating as they were always the perfect pair at school as they won competitions together and Mikan knows she will miss her once she leaves for the Alice Academy.",
        },
        {
          id: 7,
          title: "Maid-Sama!",
          url: "https://covers.openlibrary.org/b/id/10491518-L.jpg",
          originalPrice: 14.95,
          salePrice: 12.95,
          rating: 4.5,
          summary: "Brilliant and overachieving, Misaki Ayuzawa is the President of the Student Council at Seika High School, formerly a boys' school. Unfortunately, most of the students are still male and stuck in their slovenly habits, so man-hating Misaki really socks it to 'em in an attempt to make the school presentable to attract more female students. But what will she do when the sexiest boy in school finds out that after school, Misaki works in a maid cafe.",
        },
        {
          id: 8,
          title: "Vampire Knight",
          url: "https://covers.openlibrary.org/b/id/10486367-L.jpg",
          originalPrice: 11.95,
          salePrice: 10.95,
          rating: 2.5,
          summary: "Cross Academy is attended by two groups of students: the Day Class and the Night Class. At twilight, when the students of the Day Class return to their dorm, they cross paths with the Night Class on their way to school. Yuki Cross and Zero Kiryu are the Guardians of the school, protecting the Day Class from the Academy's dark secret: the Night Class is full of vampires!",
        },
        {
          id: 9,
          title: "Ranma 1/2",
          url: "https://ia800607.us.archive.org/view_archive.php?archive=/18/items/olcovers81/olcovers81-L.zip&file=813943-L.jpg",
          originalPrice: 14.95,
          salePrice: 13.95,
          rating: 4,
          summary: "Years ago, Genma promised his old friend Soun Tendo that Ranma would marry one of Soun's three daughters and carry on the family’s martial arts school. Except that the girl picked to be Ranma’s bride doesn’t seem to like him, Ranma keeps getting into fights…and did we mention that whole changing into a girl thing?",
        },
        {
          id: 10,
          title: "The Gentleman's Alliance",
          url: "https://covers.openlibrary.org/b/id/9011745-L.jpg",
          originalPrice: 14.95,
          salePrice: null,
          rating: 3.5,
          summary: "Haine joins the student council at an elite academy to get to know the boy who rescued her long ago. Haine has been in love with Shizumasa Togu since she read the fairy tale he wrote as a child. However, the Emperor is so well sequestered by the student council that she hasn't been able to speak to him in the three months she's been at the academy. And as rumor has it, he already has a lover...",
        },
        {
          id: 11,
          title: "Kodocha",
          url: "https://ia800602.us.archive.org/view_archive.php?archive=/24/items/olcovers95/olcovers95-L.zip&file=956990-L.jpg",
          originalPrice: 12.95,
          salePrice: null,
          rating: 5,
          summary: "Sana Kurata is a cheerful, popular and energetic 11-year-old child actress who enrolls in a regular school only to find out there is chaos in the classroom, led mainly by an aloof boy named Akito Hayama. At first, the two come in conflict with each other because of their opposing ideals, but as they get to know each other, they start helping each other out in Akito's family life and Sana's career, as well as helping their classmates and peers.",
        },

        {
          id: 12,
          title: "Full Moon Wo Sagashite",
          url: "https://ia801609.us.archive.org/view_archive.php?archive=/23/items/olcovers104/olcovers104-L.zip&file=1041458-L.jpg",
          originalPrice: 16.95,
          salePrice: 14.95,
          rating: 5,
          summary: "Mitsuki loves singing, but a malignant tumor in her throat has prevented her from pursuing her passion. However, Mitsuki's life turns around when two fun-loving Shinigami appear to grant her a temporary reprieve from her illness--and give her singing career a magical jump-start.",
        },
];